### ISSUE TITLE
Completed payments cannot be refunded

### ISSUE THREAD

**Issue by aksh0925** [GetOccasion/StickyBooking#69]
To replicate:
1. Go to this order - https://bookings.stickyfolios.com/orders#/order_details/jtjlwxxf
2. The order was successfully processed for $2 by Stripe

Expected:
1. I should be able to refund the transaction

Actual:
1. No payment attached.

Video:
https://www.useloom.com/share/059ccdbd7818474f9cd01e141853a65b

**Comment by kieranklaassen** [comment]
Also, I did a payment on https://app.getoccasion.com/orders#/order_details/ftdg423o.

There is payment method attached.

Possibly because we scope by merchant and the customer whose payment_method this is is not linked to the currenct merchant.


![occasion_-_reports](https://user-images.githubusercontent.com/209089/34502572-ab9fa9f8-efd9-11e7-86f5-d115f28b8ac0.png)

**Comment by nicklandgrebe** [comment]
Fixed
